[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    'forge-std=lib/forge-std/src'
]
optimizer = true
optimizer_runs = 200
solc_version = '0.8.20'
via_ir = true

[profile.ci]
fuzz_runs = 256
verbosity = 4

[rpc_endpoints]
eklesia = '${EKLESIA_RPC}'
