services:
  postgres:
    image: postgres:15
    container_name: estate_db
    restart: always
    environment:
      POSTGRES_USER: se7en
      POSTGRES_PASSWORD: sovereign
      POSTGRES_DB: estate
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  backend:
    build: ./se7en-backend
    command: npm run start
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgres://se7en:sovereign@postgres:5432/estate
      ESTATE_MODE: ${ESTATE_MODE:-DEMO}
      KMS_MODE: ${KMS_MODE:-MOCK}
      TREASURY_POLICY_ALPHA: ${TREASURY_POLICY_ALPHA:-0.75}
      TREASURY_POLICY_SPREAD_BPS: ${TREASURY_POLICY_SPREAD_BPS:-50}
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    volumes:
      - ./se7en-backend:/app
      - ./infra:/infra
      - backend_node_modules:/app/node_modules

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_EKLESIA_API_URL: http://localhost:4000
      EKLESIA_API_URL: http://backend:4000
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  pgdata:
  backend_node_modules:
